_wandb:
    value:
        cli_version: 0.22.0
        e:
            ad0wxiq36sh7j0jqa8iiokywfm3hutc5:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 96
                cpu_count_logical: 96
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "41956900864"
                        used: "11996024832"
                email: trung.le@ufl.edu
                executable: /blue/dforte/trung.le/.conda/envs/latest_env/bin/python
                git:
                    commit: 3afe23ab2154351bcb33987c1af7831814d06ac8
                    remote: https://github.com/Ben11304/Neurips2025_Weak_lensing.git
                gpu: NVIDIA L4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 7424
                      memoryTotal: "24152899584"
                      name: NVIDIA L4
                      uuid: GPU-2055c850-596d-d643-67d6-1333ad24b634
                host: c0609a-s23.ufhpc
                memory:
                    total: "810638635008"
                os: Linux-5.14.0-503.40.1.el9_5.x86_64-x86_64-with-glibc2.34
                program: /blue/dforte/trung.le/misc/Neurips2025_Weak_lensing/train.py
                python: CPython 3.13.7
                root: /blue/dforte/trung.le/misc/Neurips2025_Weak_lensing
                slurm:
                    cluster_name: hipergator
                    conf: /opt/slurm/etc/slurm.conf
                    cpus_on_node: "16"
                    cpus_per_task: "16"
                    gpus: "1"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: dforte
                    job_cpus_per_node: "16"
                    job_end_time: "1759382906"
                    job_gid: "3684"
                    job_gpus: "0"
                    job_id: "14422510"
                    job_name: vscode
                    job_nodelist: c0609a-s23
                    job_num_nodes: "1"
                    job_partition: hpg-turin
                    job_qos: dforte
                    job_start_time: "1759339706"
                    job_uid: "8957"
                    job_user: trung.le
                    jobid: "14422510"
                    localid: "0"
                    mem_per_node: "65536"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: c0609a-s23
                    nprocs: "1"
                    ntasks: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /blue/dforte/trung.le/difflogic/diff-replica-2025/slurm_out
                    submit_host: login10.ufhpc
                    task_pid: "4058330"
                    tasks_per_node: "1"
                    tmpdir: /scratch/local/14422510
                    topology_addr: ibcore.ibsw0608-s16.c0609a-s23
                    topology_addr_pattern: switch.switch.node
                    tres_per_task: cpu=16
                startedAt: "2025-10-01T18:02:00.208059Z"
                writerId: ad0wxiq36sh7j0jqa8iiokywfm3hutc5
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 13
                - 16
            "4": 3.13.7
            "5": 0.22.0
            "12": 0.22.0
            "13": linux-x86_64
BATCH_SIZE:
    value: 64
DEVICE:
    value: cuda
EPOCHS:
    value: 60
IMG_HEIGHT:
    value: 1424
IMG_WIDTH:
    value: 176
LEARNING_RATE:
    value: 2e-06
NUM_TARGETS:
    value: 2
WEIGHT_DECAY:
    value: 0.0001
epochs_per_chunk:
    value: 1
split_ratio:
    value: 0.8
