_wandb:
    value:
        cli_version: 0.22.0
        e:
            93glyhfye8zfbewqfn0f1ckvu12aekf0:
                apple:
                    ecpuCores: 6
                    gpuCores: 14
                    memoryGb: 18
                    name: Apple M3 Pro
                    pcpuCores: 5
                    ramTotalBytes: "19327352832"
                    swapTotalBytes: "5368709120"
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 11
                cpu_count_logical: 11
                disk:
                    /:
                        total: "494384795648"
                        used: "338824617984"
                email: huydv6210@gmail.com
                executable: /opt/anaconda3/envs/Neurips/bin/python
                git:
                    commit: 2c458b34b6291eccb1d29b3312d789e34e99d423
                    remote: https://github.com/Ben11304/Neurips2025_Weak_lensing.git
                host: Mac.devices.kent.edu
                memory:
                    total: "19327352832"
                os: macOS-26.1-arm64-arm-64bit
                program: /Users/viethuy/Working_space/Neurips/Neurips2025_Weak_lensing/train.py
                python: CPython 3.12.11
                root: /Users/viethuy/Working_space/Neurips/Neurips2025_Weak_lensing
                startedAt: "2025-10-01T15:50:54.859691Z"
                writerId: 93glyhfye8zfbewqfn0f1ckvu12aekf0
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 13
                - 16
            "4": 3.12.11
            "5": 0.22.0
            "8":
                - 2
            "12": 0.22.0
            "13": darwin-arm64
BATCH_SIZE:
    value: 101
DEVICE:
    value: mps
EPOCHS:
    value: 15
IMG_HEIGHT:
    value: 1424
IMG_RESIZE:
    value: 256
IMG_WIDTH:
    value: 176
LEARNING_RATE:
    value: 1e-06
NUM_TARGETS:
    value: 4
WEIGHT_DECAY:
    value: 0.0001
epochs_per_chunk:
    value: 1
split_ratio:
    value: 0.8
