_wandb:
    value:
        cli_version: 0.22.0
        e:
            17m94bu8qptq8ulnqn4kxveiaa0aqftf:
                apple:
                    ecpuCores: 6
                    gpuCores: 14
                    memoryGb: 18
                    name: Apple M3 Pro
                    pcpuCores: 5
                    ramTotalBytes: "19327352832"
                    swapTotalBytes: "2147483648"
                codePath: CNN_direct_with_2.ipynb
                codePathLocal: CNN_direct_with_2.ipynb
                cpu_count: 11
                cpu_count_logical: 11
                disk:
                    /:
                        total: "494384795648"
                        used: "349972103168"
                email: huydv6210@gmail.com
                executable: /opt/anaconda3/envs/Neurips/bin/python
                git:
                    commit: 955de1a80106a77a00596d9630b24e6e0cc2dfaf
                    remote: https://github.com/Ben11304/Neurips2025_Weak_lensing.git
                host: MacBook-Ben.local
                memory:
                    total: "19327352832"
                os: macOS-26.0-arm64-arm-64bit
                program: /Users/viethuy/Working_space/Neurips/Neurips2025_Weak_lensing/CNN_direct_with_2.ipynb
                python: CPython 3.12.11
                root: /Users/viethuy/Working_space/Neurips/Neurips2025_Weak_lensing
                startedAt: "2025-09-20T00:46:52.693456Z"
                writerId: 17m94bu8qptq8ulnqn4kxveiaa0aqftf
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 2
                - 3
                - 13
                - 16
            "4": 3.12.11
            "5": 0.22.0
            "8":
                - 1
                - 2
            "12": 0.22.0
            "13": darwin-arm64
BATCH_SIZE:
    value: 128
DEVICE:
    value: mps
EPOCHS:
    value: 10
IMG_HEIGHT:
    value: 1424
IMG_RESIZE:
    value: 256
IMG_WIDTH:
    value: 176
LEARNING_RATE:
    value: 0.0002
NUM_TARGETS:
    value: 4
WEIGHT_DECAY:
    value: 0.0001
epochs_per_chunk:
    value: 1
split_ratio:
    value: 0.8
